CREATE TABLESPACE DB_MOBILE
DATAFILE 'C:\Projetos\Oracle\DB_MOBILE.DBF' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

CREATE USER ADMMOBILE IDENTIFIED BY "102030@mobile" DEFAULT TABLESPACE DB_MOBILE;

